# Dependabot configuration for security-central
# Automatically keeps dependencies and GitHub Actions up to date
# See: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "cboyd0319"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10

  # Keep Python dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    reviewers:
      - "cboyd0319"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group all patch updates together
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Allow version updates
    versioning-strategy: increase
    open-pull-requests-limit: 10
    # Ignore specific dependencies if needed
    # ignore:
    #   - dependency-name: "some-package"
    #     versions: ["1.x", "2.x"]

  # Keep Docker dependencies up to date (if using Docker)
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   reviewers:
  #     - "cboyd0319"
  #   labels:
  #     - "dependencies"
  #     - "docker"
