blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/cboyd0319/security-central/security/advisories/new
    about: Report a security vulnerability privately
  - name: Discussions
    url: https://github.com/cboyd0319/security-central/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/cboyd0319/security-central/blob/main/README.md
    about: View project documentation
