# Common Dependencies
# Versions that should be synchronized across all repos

python:
  # Code formatting
  black: "24.10.0"
  isort: "5.13.2"
  autopep8: "2.0.4"

  # Testing
  pytest: "8.3.3"
  pytest-cov: "5.0.0"
  pytest-mock: "3.14.0"

  # Linting
  ruff: "0.6.9"
  pylint: "3.3.1"
  mypy: "1.11.2"

  # Security
  bandit: "1.7.10"
  safety: "3.2.8"

npm:
  # Testing
  "@types/jest": "^29.5.12"
  "jest": "^29.7.0"

  # Linting
  "eslint": "^9.11.1"
  "prettier": "^3.3.3"

  # React (for JobSentinel)
  "react": "^19.0.0"
  "react-dom": "^19.0.0"

github_actions:
  # Standard actions that should be kept in sync
  "actions/checkout": "v4"
  "actions/setup-python": "v5"
  "actions/setup-node": "v4"
  "actions/upload-artifact": "v4"
  "github/codeql-action/upload-sarif": "v3"
