"""
Centralized constants for security-central.
Auto-generated by replace_magic_numbers.py
"""

# HTTP Status Codes
HTTP_OK = 200  # Used in 1 places
SEND_ALERT_202 = 202  # Used in 1 places
TIMEOUT_EXTENDED = 300  # Used in 1 places
HTTP_FORBIDDEN = 403  # Used in 2 places
HTTP_NOT_FOUND = 404  # Used in 1 places
CREATE_SESSION_WITH_RETRIES_429 = 429  # Used in 1 places
HTTP_INTERNAL_ERROR = 500  # Used in 2 places
HTTP_BAD_GATEWAY = 502  # Used in 1 places
HTTP_SERVICE_UNAVAILABLE = 503  # Used in 1 places
CREATE_SESSION_WITH_RETRIES_504 = 504  # Used in 1 places

# Timeout Values (seconds)
TIMEOUT_SHORT = 30  # Used in 17 places
TIMEOUT_MEDIUM = 60  # Used in 35 places
TIMEOUT_LONG = 120  # Used in 6 places
TIMEOUT_EXTENDED = 300  # Used in 1 places
TIMEOUT_VERY_LONG = 600  # Used in 2 places

# Retry Counts
DEFAULT_RETRY_COUNT = 3  # Used in 13 places
MAX_RETRY_ATTEMPTS = 5  # Used in 11 places
MAX_ATTEMPTS = 10  # Used in 22 places

# Thresholds and Percentages
MEDIUM_THRESHOLD = 50  # Used in 2 places
GOOD_THRESHOLD = 70  # Used in 1 places
HIGH_THRESHOLD = 80  # Used in 6 places
EXCELLENT_THRESHOLD = 90  # Used in 3 places

# Other Constants
SCANNINGCONFIG_4 = 4  # Used in 5 places
DEDUPLICATE_FINDINGS_6 = 6  # Used in 2 places
SECURITYPOLICIES_7 = 7  # Used in 4 places
DEDUPLICATE_FINDINGS_8 = 8  # Used in 5 places
DEDUPLICATE_FINDINGS_9 = 9  # Used in 3 places
UPDATE_SYNC_SCRIPT_12 = 12  # Used in 1 places
SUPPLYCHAINANALYZER_15 = 15  # Used in 4 places
SUPPLYCHAINANALYZER_20 = 20  # Used in 3 places
_CHECK_RECENT_SCANS_24 = 24  # Used in 1 places
SUPPLYCHAINANALYZER_25 = 25  # Used in 1 places
CONSTANT_42 = 42  # Used in 1 places
SCAN_JVM_180 = 180  # Used in 1 places
BUFFER_SIZE_KB = 1024  # Used in 4 places
_CHECK_RECENT_SCANS_3600 = 3600  # Used in 1 places
BUFFER_SIZE_4KB = 4096  # Used in 1 places
