name: Multi-Repo Housekeeping

on:
  schedule:
    - cron: '0 3 * * 1'  # Monday 3 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyyaml requests black isort ruff

      - name: Clone all repositories
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/clone_repos.py

      - name: Sync GitHub Actions versions
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/sync_github_actions.py \
            --auto-create-pr

      - name: Sync LICENSE files
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/sync_licenses.py \
            --template config/templates/LICENSE.MIT

      - name: Update common dependencies
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/sync_common_deps.py \
            --config config/common-dependencies.yml

      - name: Enforce code quality standards
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/enforce_standards.py \
            --auto-fix

      - name: Clean up old branches
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/cleanup_branches.py \
            --older-than-days 90 \
            --exclude main,master,develop

      - name: Update documentation badges
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          python scripts/housekeeping/update_badges.py

      - name: Generate housekeeping report
        run: |
          python scripts/housekeeping/generate_housekeeping_report.py \
            --output docs/reports/housekeeping/$(date +%Y-%m-%d)-housekeeping.md

      - name: Commit report
        run: |
          git config user.name "Security Bot"
          git config user.email "security-bot@github.com"
          git add docs/reports/housekeeping/
          git commit -m "chore: housekeeping report $(date +%Y-%m-%d)" || true
          git push || true

      - name: Send summary to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_SECURITY_WEBHOOK }}
        run: |
          curl -X POST "$SLACK_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{
              \"text\": \"🧹 Weekly housekeeping complete\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*Weekly Housekeeping Report*\n\nAutomated maintenance tasks completed across all repositories.\n\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>\"
                  }
                }
              ]
            }"
