name: Secret Scanning

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Daily

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history

      - name: TruffleHog Scan
        # Use Docker directly to avoid BASE==HEAD error on push to main
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            # Scan only the latest commit on push to main
            docker run --rm -v "$PWD:/workdir" -w /workdir \
              ghcr.io/trufflesecurity/trufflehog:latest \
              git file:///workdir --since-commit HEAD~1 --only-verified
          else
            # For PRs and scheduled runs, scan the full repo
            docker run --rm -v "$PWD:/workdir" -w /workdir \
              ghcr.io/trufflesecurity/trufflehog:latest \
              filesystem /workdir --only-verified
          fi

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
